# Generated by Django 6.0.2 on 2026-03-01 11:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_otp_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='invite_code',
            field=models.CharField(blank=True, max_length=6, null=True, unique=True, validators=[django.core.validators.RegexValidator(message='Only letters and numbers are allowed.', regex='^[A-Za-z0-9]+$')]),
        ),
    ]
