services:
  db:
    image: postgres:16
    container_name: referral_db
    restart: always
    env_file:
      - .env
    volumes:
      - referral_postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  web:
    build: .
    container_name: referral_web
    command: python src/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env

volumes:
  referral_postgres_data:
